/* import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers/chakraUI";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
 */

import "./css/style.css";

// import { Inter } from "next/font/google";
import "./globals.css";
import Theme from "./theme-provider";
import AppProvider from "./app-provider";
import Sidebar from "@/components/ui/sidebar";
import Header from "@/components/ui/header";
import { Providers } from "./providers/chakraUI";

/* const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
}); */

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <Providers>
          <Theme>
            <AppProvider>
              <div className="flex h-[100dvh] overflow-hidden">
                <Sidebar />
                <div className="relative flex flex-col flex-1 overflow-y-auto overflow-x-hidden">
                  <Header />

                  <main className="grow [&>*:first-child]:scroll-mt-16">
                    {children}
                  </main>
                </div>
              </div>
            </AppProvider>
          </Theme>
        </Providers>
      </body>
    </html>
  );
}
